### ISSUE TITLE
gives error on installing on windows

### ISSUE THREAD

**Issue by bawzz234** [juliendu11/NodeJS-Proxy-CheckerV2#1]
Hello, 

Just tried to install but giving the bellow error:
`npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "nodejs-proxy-checkerv2" under a package
npm ERR! also called "nodejs-proxy-checkerv2". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-02-23T14_33_21_44
0Z-debug.log
`

**Comment by juliendu11** [comment]
Hi, I updated the package normally the problem is solved, update the package
