### ISSUE TITLE
All proxies results of ProxyAnonymousLevel are "Unknown"

### ISSUE THREAD

**Issue by LoSunny** [juliendu11/NodeJS-Proxy-CheckerV2#2]
Whenever I try to test some proxies, all of them has an "Unknown" ProxyAnonymousLevel.

**Comment by juliendu11** [comment]
Are your proxies alive? Did you add a proxy judge or used .addDefaultProxyJudge() for load default proxy judge ?

**Comment by LoSunny** [comment]
Some of the proxies are alive, but all of them have "Unknown" in "ProxyAnonymousLevel".
Here is my code:
```
let json = {};
for (var i = json.length - 1; i >= 0; i--) {
    instance.addOnly1Proxy(json[i].proxy)
}
instance.addDefaultProxyJudge().addDefaultProxyInformationProvider();
await instance.check(null).then(res=>{
    console.log(res)
})
```

**Comment by juliendu11** [comment]
Try by replacing .addDefaultProxyJudge() with .addProxyJudge ("http://www.knowops.com/cgi-bin/textenv.pl")
It is surely a proxy judge link that no longer works.

````
let json = {};
for (var i = json.length - 1; i >= 0; i--) {
    instance.addOnly1Proxy(json[i].proxy)
}
instance.addProxyJudge("http://www.knowops.com/cgi-bin/textenv.pl").addDefaultProxyInformationProvider();
await instance.check(null).then(res=>{
    console.log(res)
})
````

**Comment by LoSunny** [comment]
Oh thanks, it works now
